# Generated by Django 4.0 on 2024-03-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahifa', '0003_event_eventimage_eventru_delete_tadbir_lavhalari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id']},
        ),
    ]
