# Generated by Django 4.0 on 2024-03-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahifa', '0005_alter_aboutus_options_alter_corusel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['id'], 'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': 'Tadbir', 'verbose_name_plural': 'Tadbirlar'},
        ),
        migrations.AlterModelOptions(
            name='statiska',
            options={'ordering': ['id'], 'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistika'},
        ),
    ]
