# Generated by Django 4.0 on 2024-03-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('olchami', models.CharField(blank=True, max_length=20, null=True)),
                ('Rasm', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qoshimcha_xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
                ('narxi', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toifalash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToifalashRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('toifalash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toifalash_ru', to='pasuda_qoshish.toifalash')),
            ],
        ),
        migrations.CreateModel(
            name='Taomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('Rasm', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('narxi', models.IntegerField()),
                ('toifasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasuda_qoshish.toifalash')),
            ],
        ),
        migrations.CreateModel(
            name='Stul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('olchami', models.CharField(blank=True, max_length=20, null=True)),
                ('Rasm', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('narxi', models.IntegerField()),
                ('toifasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasuda_qoshish.toifalash')),
            ],
        ),
        migrations.CreateModel(
            name='maxsulotRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('maxsulot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulot_ru', to='pasuda_qoshish.maxsulot')),
            ],
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='toifasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasuda_qoshish.toifalash'),
        ),
    ]
