# Generated by Django 4.0 on 2024-03-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasuda_qoshish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxsulot',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='qoshimcha_xizmatlar',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stul',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='taomlar',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='toifalash',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='TaomlarRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ru', to='pasuda_qoshish.taomlar')),
            ],
        ),
        migrations.CreateModel(
            name='StulRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('chair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chair_ru', to='pasuda_qoshish.stul')),
            ],
        ),
        migrations.CreateModel(
            name='QoshimchaXizmatlarRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_ru', to='pasuda_qoshish.qoshimcha_xizmatlar')),
            ],
        ),
    ]
