# Generated by Django 4.0 on 2024-03-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasuda_qoshish', '0002_alter_maxsulot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxsulot',
            options={'ordering': ['id'], 'verbose_name': 'Maxsulot', 'verbose_name_plural': 'Maxsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='qoshimcha_xizmatlar',
            options={'ordering': ['id'], 'verbose_name': "Qo'shimcha xizmat", 'verbose_name_plural': "Qo'shimcha xizmatlar"},
        ),
        migrations.AlterModelOptions(
            name='stul',
            options={'ordering': ['id'], 'verbose_name': 'Stul', 'verbose_name_plural': 'Stullar'},
        ),
        migrations.AlterModelOptions(
            name='taomlar',
            options={'ordering': ['id'], 'verbose_name': 'Taom', 'verbose_name_plural': 'Taomlar'},
        ),
        migrations.AlterModelOptions(
            name='toifalash',
            options={'ordering': ['id'], 'verbose_name': 'Toifa', 'verbose_name_plural': 'Toifalar'},
        ),
    ]
