# Generated by Django 4.0 on 2024-02-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasuda_qoshish', '0002_taomlar_stul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qoshimcha_xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
                ('narxi', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
