# Generated by Django 4.0 on 2024-03-29 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_saleru_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleru',
            name='sale',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sale_ru', to='orders.sale'),
        ),
    ]
