# Generated by Django 4.0 on 2024-03-29 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pasuda_qoshish', '0003_alter_maxsulot_options_and_more'),
        ('orders', '0003_alter_saleru_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='pasuda_qoshish.qoshimcha_xizmatlar')),
            ],
            options={
                'verbose_name': "Qo'shimcha xizmat",
                'verbose_name_plural': "Qo'shimcha xizmatlar",
            },
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='pasuda_qoshish.taomlar')),
            ],
            options={
                'verbose_name': 'Ovqat buyurtma',
                'verbose_name_plural': 'Ovqat buyurtmalar',
            },
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StulOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stul_orders', to='pasuda_qoshish.stul')),
            ],
            options={
                'verbose_name': 'Stul buyurtma',
                'verbose_name_plural': 'Stul buyurtmalar',
            },
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.CreateModel(
            name='StulOrderRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_ru', to='orders.stulorder')),
            ],
        ),
        migrations.AddField(
            model_name='stulorder',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stul_orders', to='orders.sale'),
        ),
        migrations.CreateModel(
            name='FoodOrderRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_ru', to='orders.foodorder')),
            ],
        ),
        migrations.AddField(
            model_name='foodorder',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='orders.sale'),
        ),
        migrations.CreateModel(
            name='ExtraServiceOrderRu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_ru', to='orders.extraserviceorder')),
            ],
        ),
        migrations.AddField(
            model_name='extraserviceorder',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='orders.sale'),
        ),
    ]
